# Generated by Django 5.2.13 on 2026-04-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Bus name/number', max_length=100)),
                ('bus_type', models.CharField(choices=[('AC', 'AC'), ('NON_AC', 'Non-AC'), ('SLEEPER', 'Sleeper'), ('SEMI_SLEEPER', 'Semi-Sleeper')], default='AC', max_length=15)),
                ('total_seats', models.PositiveIntegerField(default=40)),
                ('registration_number', models.CharField(help_text='Vehicle registration number', max_length=20, unique=True)),
                ('amenities', models.TextField(blank=True, default='', help_text='Comma-separated amenities (e.g., WiFi, Charging Point, Blanket)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bus',
                'verbose_name_plural': 'Buses',
                'db_table': 'buses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('distance_km', models.PositiveIntegerField(blank=True, help_text='Distance in kilometers', null=True)),
                ('duration_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated duration in hours', max_digits=5, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Route',
                'verbose_name_plural': 'Routes',
                'db_table': 'routes',
                'ordering': ['source', 'destination'],
                'unique_together': {('source', 'destination')},
            },
        ),
    ]
